#This script is run on a new system and preforms installation of all my programs that I need
sudo -i
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
apt-get install 
